worker-threads: 6
worker-fs-threads: 6
worker-monitor-threads: 2
event-threads: 2

logger-level: warning

is-testing: false

server-port: 8080

# secdist-path: /configs/secure_data.json
cassandra-keyspace: store
