components_manager:
    event_thread_pool: # ev pools to deal with OS events
        threads: $event-threads
        threads#fallback: 2
    task_processors: # Task processor is an executor for coroutine tasks
        main-task-processor: # Make a task processor for CPU-bound coroutine tasks.
            worker_threads: $worker-threads # Process tasks in 4 threads.

        fs-task-processor: # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

        monitor-task-processor: # for monitoring
            thread_name: mon-worker
            worker_threads: $worker-monitor-threads
            worker_threads#fallback: 1

    default_task_processor: main-task-processor

    components: # Configuring components that were registered via component_list
        server:
            listener: # configuring the main listening socket...
                port: $server-port # ...to listen on this port and...
                task_processor: main-task-processor # ...process incoming requests on this task processor.
            listener-monitor:
                # Listen on localhost:8085 for developer/utility requests
                port: $monitor-server-port
                port#fallback: 8086
                connection:
                    in_buffer_size: 32768
                    requests_queue_size_threshold: 100
                task_processor: monitor-task-processor
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: "@stderr"
                    level: $logger-level
                    overflow_behavior: discard # Drop logs if the system is too busy to write them down.

        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            # For most of userver dynamic configs, defaults are used, some are overridden here.
            # See userver "dynamic config" docs for what configs exist.
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000

        testsuite-support: {}

        congestion-control:

        secdist: {}
        default-secdist-provider:
            config: $secdist-path
            config#env: SECDIST_PATH


        http-client:
          core-component: http-client-core
        http-client-core:
          fs-task-processor: fs-task-processor
          user-agent#fallback: 'userver-based-service 3.0'

        dns-client:
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        cassandra-view:
            path: /cassandra
            method: POST
            task_processor: main-task-processor

        cassandra-component:
            keyspace: $cassandra-keyspace

        handler-log-level:
            path: /service/log-level/{level}
            method: GET,PUT
            task_processor: monitor-task-processor
